"""add_users

Revision ID: be9893939a59
Revises: 01c1151f5b52
Create Date: 2025-08-03 19:39:48.172257

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from db import Password


# revision identifiers, used by Alembic.
revision: str = 'be9893939a59'
down_revision: Union[str, Sequence[str], None] = '01c1151f5b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('password', Password(length=156), nullable=False),
                    sa.Column('access_level',
                              sa.Enum('user', 'support', 'moderator', 'administrator', name='accesslevel'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('user_sessions',
                    sa.Column('token', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
